[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
 
[etherscan]
baseSepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
